name: Sync to Secondary Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Push to secondary repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT_TOKEN }}
        with:
          source-directory: '.'
          destination-github-username: 'oyeowart'
          destination-repository-name: 'H4K'
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: main
